<?php

require_once('../lib/Request.php');

/**
 * Test class for \lib\Request.
 * Generated by PHPUnit on 2011-10-11 at 16:44:49.
 */
class RequestTest extends PHPUnit_Framework_TestCase {
	/**
	 * @var \lib\Request
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new \lib\Request;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
	}

	public function testXHR() {
		$this->assertFalse($this->object->xhr);
	}

	public function testMethod() {
		$this->assertEquals('CLI', $this->object->method);
	}

	public function testSchema() {
		$this->assertNull($this->object->schema);
	}

	public function testDomain() {
		$this->assertNull($this->object->domain);
	}

	public function testDir() {
		$this->assertNotNull($this->object->dir);
	}

	public function testBaseName() {
		$this->assertNull($this->object->baseName);
	}

	public function testClientIP() {
		$this->assertNull($this->object->clientIP);
	}

	public function testLang() {
		$this->assertNull($this->object->lang);
	}

	public function testController() {
		$this->assertEmpty($this->object->controller);
	}

	public function testAction() {
		$this->assertNull($this->object->action);
	}
/*
	public function testUrl() {
		$this->assertEmpty($this->object->url);
	}
*/
	public function testSelf() {
		$this->assertEmpty($this->object->self);
	}

	public function testIdentifier() {
		$this->assertEmpty($this->object->identifier);
	}
}